### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "test",
  "password": "abc135!"
}

### 가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "test12345",
  "name": "testName",
  "password": "abc135!"
}

### 모든 유저 리스트 가져오기 (로그인 사용자만 접근)
GET http://localhost:8080/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzNDUiLCJleHAiOjE3MzExMjAyMTJ9.Li5h_nH8BsKDlEQ5EzIqwCi9s1XSf8C_C4tPCXcPn5E6qhFxxX_iuZ62W6qxmy7ujYjlr7A9jDF5r767RY9_Wg


### 유저 본인 정보 가져오기
GET http://localhost:8080/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzNDUiLCJleHAiOjE3MzExMjAyMTJ9.Li5h_nH8BsKDlEQ5EzIqwCi9s1XSf8C_C4tPCXcPn5E6qhFxxX_iuZ62W6qxmy7ujYjlr7A9jDF5r767RY9_Wg

### 유저 본인 정보 수정
PUT http://localhost:8080/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzNDUiLCJleHAiOjE3MzExMjAyMTJ9.Li5h_nH8BsKDlEQ5EzIqwCi9s1XSf8C_C4tPCXcPn5E6qhFxxX_iuZ62W6qxmy7ujYjlr7A9jDF5r767RY9_Wg

{
  "username": "test123",
  "name": "testNameModfy33",
  "password": "abc135!"
}

### 유저 삭제(탈퇴)
DELETE http://localhost:8080/users/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzNDUiLCJleHAiOjE3MzExMjAyMTJ9.Li5h_nH8BsKDlEQ5EzIqwCi9s1XSf8C_C4tPCXcPn5E6qhFxxX_iuZ62W6qxmy7ujYjlr7A9jDF5r767RY9_Wg

{
  "username": "test",
  "name": "testNameModfy",
  "password": "abc135!"
}

### 게시물 추가
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMTM5OTI5fQ.3khxNN8xr-F20Qf9ATH3PK4GdtwNtj0UKk0MNZmJUQ9rG7TxDhR1of293Lp7T3y3FVYGjt1-po_YzaK9t6FoWA

{
  "title": "test title1",
  "content": "test content1"
}

### 본인 게시물 수정
PUT http://localhost:8080/posts/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMTM5OTI5fQ.3khxNN8xr-F20Qf9ATH3PK4GdtwNtj0UKk0MNZmJUQ9rG7TxDhR1of293Lp7T3y3FVYGjt1-po_YzaK9t6FoWA

{
  "title": "test title",
  "content": "test content modify"
}

### 본인 게시물 삭제
DELETE http://localhost:8080/posts/17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMTM5OTI5fQ.3khxNN8xr-F20Qf9ATH3PK4GdtwNtj0UKk0MNZmJUQ9rG7TxDhR1of293Lp7T3y3FVYGjt1-po_YzaK9t6FoWA

### 본인 게시물 호출
GET http://localhost:8080/posts/18
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMTM5OTI5fQ.3khxNN8xr-F20Qf9ATH3PK4GdtwNtj0UKk0MNZmJUQ9rG7TxDhR1of293Lp7T3y3FVYGjt1-po_YzaK9t6FoWA

### 인증
GET http://localhost:8080/protected
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMDY4MzE2fQ.fc_V2igotAv-ducmOuXkea90os_4wobuqrU1qEeyzw5KyhkIEIxA1Tjy_qTZH0iJbrqCQs6QkWAjY3ygMMQluQ

