### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "test1234",
  "password": "abc135!"
}

### 가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "test1234",
  "name": "testName",
  "password": "abc135!"
}

### 유저 본인 정보 가져오기
GET http://localhost:8080/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzNCIsImV4cCI6MTczMTExNjkwN30.p3jZw-M0Zkj2xhKcua_pTeF0qJEW9UDgcWVf2EjieeeCnlfVGBSyh-ywSc1ChaUBb-PS95YUXOXOdvcudaDpLQ

### 유저 본인 정보 수정
PUT http://localhost:8080/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzIiwiZXhwIjoxNzMxMTE2Mjk4fQ.0AbG4RQIeuXHJdLfsD0Mfda2i2RB4zwn0_UhtmxXgqevF2bFFfZLg9FwMEWn6Ge5cB4RtD0pk0Sr-HFgJVJweQ

{
  "username": "test123",
  "name": "testNameModfy33",
  "password": "abc135!"
}

### 유저 삭제(탈퇴)
DELETE http://localhost:8080/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMTEzNjQ3fQ.HUudeHSCP8kyL4HtHPJI5Yx07R6sMNtay8gMJbC110fTCEoco-MvDQJR1Fca-UIwBqktkm62CK__IpweE6v_Rg

{
  "username": "test",
  "name": "testNameModfy",
  "password": "abc135!"
}

### 게시물 추가
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzNCIsImV4cCI6MTczMTExNzAyOH0.sZVjc00JLE-OS4-Xl4RKUxdS-8BbJN3QkbTIP2qjW-BvgFX5CTw-VLgFemhHieQ2PjlMF7dmYx3tgMG0NrBPRg

{
  "title": "test title1",
  "content": "test content1"
}

### 본인 게시물 수정
PUT http://localhost:8080/posts/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0MTIzNCIsImV4cCI6MTczMTExNzAyOH0.sZVjc00JLE-OS4-Xl4RKUxdS-8BbJN3QkbTIP2qjW-BvgFX5CTw-VLgFemhHieQ2PjlMF7dmYx3tgMG0NrBPRg

{
  "title": "test title",
  "content": "test content modify"
}

### 본인 게시물 삭제
DELETE http://localhost:8080/posts/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMDcxMDE2fQ.v2rpbaRmqolEsGp9cqObDKuec1PvkA4qJzWCVQIOjXm6YOPwULYl6HbqbMhRQIeXjfcInhjDFBy1MbF37Sw5iA

### 게시물 호출
GET http://localhost:8080/protected
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzMxMDY4MzE2fQ.fc_V2igotAv-ducmOuXkea90os_4wobuqrU1qEeyzw5KyhkIEIxA1Tjy_qTZH0iJbrqCQs6QkWAjY3ygMMQluQ

